### ISSUE TITLE
Add nemesis consoles to docker compose

### ISSUE THREAD

**Issue by gochev** [nemesis-software/nemesis-docker#3]
The nemesis consoles should be also available in the docker compose 

This depends on #4

**Comment by marslatt** [comment]
IMPORTANT!
For runnig nemesis-console-v2 with docker-compose it is obligatory to add the following line to /etc/hosts ->  "127.0.0.1 solar.local" as 'solar.local' is used for mapping in nemesis-docker/docker-compose.yml  and  nemesis-console-v2/src/main/resources/application-docker.properties.
